[project]
name = 'Cross-Border'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Cross-Border]
path = 'contracts/Cross-Border.clar'
clarity_version = 3
epoch = 3.1
[contracts.Loyalty-Rewards-System]
path = 'contracts/Loyalty-Rewards-System.clar'
clarity_version = 3
epoch = 3.1
[contracts.Multi-Sig-Authorization]
path = 'contracts/Multi-Sig-Authorization.clar'
clarity_version = 3
epoch = 3.1
[contracts.Dispute-Resolution]
path = 'contracts/Dispute-Resolution.clar'
clarity_version = 3
epoch = 3.1
[contracts.Fee-Refund-Pool]
path = 'contracts/Fee-Refund-Pool.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
